export enum IPC_EVENTS {
  X_PLANE_CONNECTION_STATUS = 'X_PLANE_CONNECTION_STATUS',
  X_PLANE_CONNECTION_STATUS_REQUEST = 'X_PLANE_CONNECTION_STATUS_REQUEST',
  FRONTEND_READY = 'FRONTEND_READY',
  X_PLANE_DATAREFS = 'X_PLANE_DATAREFS',
  LOGIN = 'LOGIN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  NEW_TOKENS = 'NEW_TOKENS',
}
